### ISSUE TITLE
Segmentation fault in case a website would open a file picker on the host

### ISSUE THREAD

**Issue by SRAZKVT** [obsproject/obs-browser#384]
### Operating System Info

Other

### Other OS

Void Linux

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/Xi6IH3xMndBH73pD

### Expected Behavior

In interaction mode with the browser, a filepicker would be opened when necessary, allowing to choose a file.

### Current Behavior

OBS completely crashes, due to a segmentation fault.

### Steps to Reproduce

1. Set as target any website that would open a filepicker.
2. Enter interact mode with the browser.
3. Do the action that would open the filepicker.
4. OBS should close instantly.

### Anything else we should know?

Both me and a friend have tried reproducing this, both on the flatpak version, it crashes every time.

**Comment by WizardCM** [comment]
I can confirm this occurs on the Flatpak on GNOME, including when building my own Flatpak using Builder. It does not occur on standard builds.

This occurs both in **both** browser docks and browser sources. Note that while using the file picker in browser sources is not officially supported, crashing is never a solution.

Annoyingly, I'm unable to get debug symbols to load with my local OBS/CEF build, and the CEF `debug.log` terminates immediately, so it doesn't log whatever goes wrong within CEF in this situation. I will continue trying to track down this bug.

**Comment by Refragg** [comment]
Coming from https://github.com/obsproject/obs-studio/issues/8012, since the issues seem related, thought i'd also say that for me, thje crash happens on both the ppa package, custom build from source and flatpak so i don't think it's a flatpak related issue

**Comment by WizardCM** [comment]
@Refragg What desktop environment are you using?

**Comment by Refragg** [comment]
I'm on Ubuntu MATE 22.10, a friend of mine also reproduced this issue on Linux Mint Cinnamon 21.1

**Comment by WizardCM** [comment]
Hmm, that's helpful. As I'm on 22.04 LTS, I can't reproduce - even on MATE, but I'll try on 22.10.

**Comment by ChristianMRichter** [comment]
The issue is reproducable in Ubuntu 22.04 LTS. (at least in Browser Dock)

**Comment by SRAZKVT** [comment]
I can confirm it still happens in latest flatpak release, and i unfortunately haven't found a workaround as of yet.

**Comment by sankaest** [comment]
Is that issue still open? Or I miss something?
As my OBS (30.0.2) installed either via PPA or Flatpack on Ubuntu 22.04 crashes while trying open a file in browser (in Dock, like Lower Third plugin, or just in browser). Also tried older versions of OBS (like 29.1.2) and still the same result - OBS closes its self while trying to open file manager via <input type="file">.

**Comment by SRAZKVT** [comment]
Yes this issue is still open, if it wasn't, it would've been marked as closed

**Comment by david672orford** [comment]
Got a backtrace on this, but I is missing a lot of symbols. I'm not sure how to get a better trace with the source file and line number.
<pre>
Thread 74 "CrBrowserMain" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff43df9640 (LWP 1178)]
0x00007fff83710b41 in ?? () from /usr/local//lib/obs-plugins/libcef.so
(gdb) 
(gdb) 
(gdb) 
(gdb) bt
#0  0x00007fff83710b41 in  () at /usr/local//lib/obs-plugins/libcef.so
#1  0x000000000000000b in  ()
#2  0x00007ffee42f3d10 in  ()
#3  0x00007ffee4301920 in  ()
#4  0x00007ffeec016380 in  ()
#5  0x00007ffee4301950 in  ()
#6  0x00007ffff3ca5453 in __GI___libc_free (mem=<optimized out>) at ./malloc/malloc.c:3391
#7  0x00007ffee4237fc0 in  ()
#8  0x00007fff43df7690 in  ()
#9  0x00007fff81589357 in  () at /usr/local//lib/obs-plugins/libcef.so
#10 0x00007fff43df7af0 in  ()
#11 0x00007ffee4237fc0 in  ()
#12 0x0000000000000000 in  ()
</pre>
